import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { fontOswald, fontGrotesk, fontInter } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Muse Group Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontGrotesk.variable,
          fontOswald.variable,
          fontInter.variable,
          "font-grotesk"
        )}
      >
        <Navbar />
        <main
          className={cn(
            "overflow-clip", // keeps content intact including sticky elements
            "mx-auto"
          )}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
